apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
#define the cluster
metadata:
  #user-defined name of the cluster; string
  name: vks-chekhov-01
  #kubernetes namespace for the cluster; string
  namespace: vks-chekhov
#define the desired state of cluster
spec:
  #specify the cluster network; required, there is no default
  clusterNetwork:
    #network ranges from which service VIPs are allocated
    services:
      #ranges of network addresses; string array
      #CAUTION: must not overlap with Supervisor
      cidrBlocks: ["192.168.10.0/26"]
    #network ranges from which Pod networks are allocated
    pods:
      #ranges of network addresses; string array
      #CAUTION: must not overlap with Supervisor
      cidrBlocks: ["172.26.0.64/24"]
    #domain name for services; string
    serviceDomain: "chekhovspun.local"
  #specify the topology for the cluster
  topology:
    #name of the ClusterClass object to derive the topology
    class: builtin-generic-v3.3.0
    #kubernetes version of the cluster; format is TKR NAME
    version: v1.33.3
    #describe the cluster control plane
    controlPlane:
      #number of control plane nodes
      #integer value 1 or 3
      #NOTE: Production clusters require 3 control plane nodes
      replicas: 1
    #describe the cluster worker nodes
    workers:
      #specifies parameters for a set of worker nodes in the topology
      machineDeployments:
        #node pool class used to create the set of worker nodes
        - class: node-pool
          #user-defined name of the node pool; string
          name: node-pool-1
          #number of worker nodes in this pool; integer 0 or more
          replicas: 1
    #customize the cluster
    variables:
      #virtual machine class type and size for cluster nodes
      - name: vmClass
        value: best-effort-xsmall
      #persistent storage class for cluster nodes
      - name: storageClass
        value: vks-simple
      # default storageclass for control plane and worker node pools
      # - name: defaultStorageClass
      #  value: vks-policy